In [27]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [28]:
dataset = pd.read_csv('DataSYS.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [29]:
print(x)

[['Indonesian' 44.0 72000]
 ['japan' 27.0 48000]
 ['Singapore' 30.0 54000]
 ['Kamboja' 38.0 61000]
 ['Thailand' 40.0 43000]
 ['Tiongkok' 35.0 58000]
 ['India' nan 52000]
 ['Vietnam' 48.0 79000]
 ['Filipina' 50.0 83000]]


In [30]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No']


In [31]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [32]:
print(x)

[['Indonesian' 44.0 72000.0]
 ['japan' 27.0 48000.0]
 ['Singapore' 30.0 54000.0]
 ['Kamboja' 38.0 61000.0]
 ['Thailand' 40.0 43000.0]
 ['Tiongkok' 35.0 58000.0]
 ['India' 39.0 52000.0]
 ['Vietnam' 48.0 79000.0]
 ['Filipina' 50.0 83000.0]]


In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [34]:
print(x)

  (0, 2)	1.0
  (0, 9)	44.0
  (0, 10)	72000.0
  (1, 8)	1.0
  (1, 9)	27.0
  (1, 10)	48000.0
  (2, 4)	1.0
  (2, 9)	30.0
  (2, 10)	54000.0
  (3, 3)	1.0
  (3, 9)	38.0
  (3, 10)	61000.0
  (4, 5)	1.0
  (4, 9)	40.0
  (4, 10)	43000.0
  (5, 6)	1.0
  (5, 9)	35.0
  (5, 10)	58000.0
  (6, 1)	1.0
  (6, 9)	39.0
  (6, 10)	52000.0
  (7, 7)	1.0
  (7, 9)	48.0
  (7, 10)	79000.0
  (8, 0)	1.0
  (8, 9)	50.0
  (8, 10)	83000.0


In [35]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [36]:
print(y)

[0 1 0 0 1 1 0 1 0]


In [54]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.1, random_state= 1)

TypeError: Singleton array array(<9x11 sparse matrix of type '<class 'numpy.float64'>'
	with 27 stored elements in Compressed Sparse Row format>, dtype=object) cannot be considered a valid collection.

In [ ]:
print(x_train)

NameError: name 'x_train' is not defined

In [ ]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_test)

[0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
